ARG DEBIAN_RELEASE
FROM debian:${DEBIAN_RELEASE}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    openssh-client \
    gcc \
    libc6-dev \
    pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
